@baseUrl = http://localhost:4000/api/v1
@authToken = {{login.response.headers.X-AuthToken}}

# @name login

###
POST {{baseUrl}}/api/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

###

# USERS
### REGISTER

POST {{baseUrl}}/register
# Authorization: Bearer xxx
Content-Type: application/json

{
  "name": "Kaike Cardoso",
  "email": "kaike.c.lima@hotmail.com",
  "password": "26201145Ac@"
}

###
DELETE  {{baseUrl}}/users/71c569f7-b437-4c64-9d20-2d3bd9217e11 HTTP/1.1
Content-Type: application/json

###
GET  {{baseUrl}}/users/90c8a659-2be5-4322-baa0-56500dbd55c3 HTTP/1.1
Content-Type: application/json

