@baseUrl = http://localhost:4000/api/v1

# USERS
### REGISTER

POST {{baseUrl}}/register
Content-Type: application/json

{
  "name": "Cl",
  "email": "claudio.c.lima@hotmail.com",
  "password": "Java262011@#"
}
