services:
    postgres:
        container_name: postgres
        restart: always
        image: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: prostore
            PGDATA: /data/postgres
        volumes:
            - ./backend/data/pg:/data/postgres
